// for seeding caregivers data

// import { client, dbConnect } from "../lib/dbConnect";

// const caregiversData = [
//   {
//     id: "cg001",
//     name: "Dr. Fatima Rahman",
//     role: "Pediatric Specialist",
//     experience: "10 years",
//     rating: 4.9,
//     reviews: 156,
//     image: "https://randomuser.me/api/portraits/women/32.jpg",
//     specialties: ["Newborn Care", "Child Development", "Vaccination"],
//     hourlyRate: 450,
//     availability: "Full-time",
//     location: "Dhaka",
//     languages: ["Bangla", "English", "Arabic"],
//     verified: true,
//     responseTime: "15 mins",
//     email: "fatima.rahman@carenow.com",
//     phone: "+8801712345678",
//     about:
//       "Pediatric specialist with 10+ years experience in child healthcare and development.",
//     education: ["MBBS, DCH", "Pediatrics Specialist"],
//   },
//   {
//     id: "cg002",
//     name: "Rahim Uddin",
//     role: "Elderly Care Expert",
//     experience: "15 years",
//     rating: 4.8,
//     reviews: 132,
//     image: "https://randomuser.me/api/portraits/men/75.jpg",
//     specialties: ["Dementia Care", "Post-Stroke Recovery", "Physiotherapy"],
//     hourlyRate: 400,
//     availability: "24/7",
//     location: "Chittagong",
//     languages: ["Bangla", "Hindi", "English"],
//     verified: true,
//     responseTime: "10 mins",
//     email: "rahim.uddin@carenow.com",
//     phone: "+8801712345679",
//     about:
//       "Specialized in elderly care with expertise in dementia and post-stroke recovery.",
//     education: ["B.Sc Nursing", "Geriatric Care Certification"],
//   },
//   {
//     id: "cg003",
//     name: "Ayesha Chowdhury",
//     role: "Special Needs Specialist",
//     experience: "8 years",
//     rating: 4.7,
//     reviews: 98,
//     image: "https://randomuser.me/api/portraits/women/44.jpg",
//     specialties: ["Autism Support", "Speech Therapy", "Behavioral Therapy"],
//     hourlyRate: 500,
//     availability: "Flexible",
//     location: "Dhaka",
//     languages: ["Bangla", "English", "Sign Language"],
//     verified: true,
//     responseTime: "20 mins",
//     email: "ayesha.chowdhury@carenow.com",
//     phone: "+8801712345680",
//     about:
//       "Special needs care expert with extensive training in autism and behavioral therapy.",
//     education: ["Special Education Degree", "Autism Specialist"],
//   },
//   {
//     id: "cg004",
//     name: "Mohammad Ali",
//     role: "Post-Surgery Care",
//     experience: "12 years",
//     rating: 4.6,
//     reviews: 87,
//     image: "https://randomuser.me/api/portraits/men/81.jpg",
//     specialties: [
//       "Post-Operation Care",
//       "Wound Dressing",
//       "Medication Management",
//     ],
//     hourlyRate: 380,
//     availability: "Full-time",
//     location: "Sylhet",
//     languages: ["Bangla", "English", "Urdu"],
//     verified: true,
//     responseTime: "25 mins",
//     email: "mohammad.ali@carenow.com",
//     phone: "+8801712345681",
//     about:
//       "Expert in post-surgical care with nursing background and emergency response training.",
//     education: ["Diploma in Nursing", "Critical Care Certification"],
//   },
//   {
//     id: "cg005",
//     name: "Nadia Islam",
//     role: "Newborn Care Specialist",
//     experience: "6 years",
//     rating: 4.9,
//     reviews: 145,
//     image: "https://randomuser.me/api/portraits/women/68.jpg",
//     specialties: ["Premature Baby Care", "Lactation Support", "Sleep Training"],
//     hourlyRate: 420,
//     availability: "Part-time",
//     location: "Dhaka",
//     languages: ["Bangla", "English"],
//     verified: true,
//     responseTime: "30 mins",
//     email: "nadia.islam@carenow.com",
//     phone: "+8801712345682",
//     about:
//       "Specialized in newborn care with focus on premature babies and lactation support.",
//     education: ["Midwifery Certification", "Neonatal Care Training"],
//   },
//   {
//     id: "cg006",
//     name: "Kamal Hossain",
//     role: "Physical Therapy Expert",
//     experience: "9 years",
//     rating: 4.5,
//     reviews: 76,
//     image: "https://randomuser.me/api/portraits/men/45.jpg",
//     specialties: ["Physical Therapy", "Mobility Training", "Rehabilitation"],
//     hourlyRate: 550,
//     availability: "Flexible",
//     location: "Rajshahi",
//     languages: ["Bangla", "English"],
//     verified: true,
//     responseTime: "40 mins",
//     email: "kamal.hossain@carenow.com",
//     phone: "+8801712345683",
//     about:
//       "Physical therapy specialist with expertise in mobility training and rehabilitation.",
//     education: ["Physiotherapy Degree", "Rehabilitation Specialist"],
//   },
//   {
//     id: "cg007",
//     name: "Sabrina Ahmed",
//     role: "Dementia Care Specialist",
//     experience: "11 years",
//     rating: 4.8,
//     reviews: 103,
//     image: "https://randomuser.me/api/portraits/women/26.jpg",
//     specialties: ["Alzheimer's Care", "Memory Care", "Cognitive Therapy"],
//     hourlyRate: 480,
//     availability: "Full-time",
//     location: "Dhaka",
//     languages: ["Bangla", "English"],
//     verified: true,
//     responseTime: "15 mins",
//     email: "sabrina.ahmed@carenow.com",
//     phone: "+8801712345684",
//     about:
//       "Specialized in dementia and Alzheimer's care with cognitive therapy expertise.",
//     education: ["Psychology Degree", "Dementia Care Certification"],
//   },
//   {
//     id: "cg008",
//     name: "Arif Khan",
//     role: "Emergency Care Nurse",
//     experience: "7 years",
//     rating: 4.7,
//     reviews: 92,
//     image: "https://randomuser.me/api/portraits/men/22.jpg",
//     specialties: ["Emergency Response", "First Aid", "CPR Training"],
//     hourlyRate: 520,
//     availability: "24/7",
//     location: "Khulna",
//     languages: ["Bangla", "English"],
//     verified: true,
//     responseTime: "5 mins",
//     email: "arif.khan@carenow.com",
//     phone: "+8801712345685",
//     about:
//       "Emergency care specialist with rapid response training and critical care experience.",
//     education: ["Emergency Nursing", "Advanced Life Support"],
//   },
//   {
//     id: "cg009",
//     name: "Tasnim Rahman",
//     role: "Nutrition & Diet Care",
//     experience: "5 years",
//     rating: 4.6,
//     reviews: 67,
//     image: "https://randomuser.me/api/portraits/women/55.jpg",
//     specialties: ["Diet Planning", "Nutrition Therapy", "Special Diets"],
//     hourlyRate: 350,
//     availability: "Part-time",
//     location: "Dhaka",
//     languages: ["Bangla", "English"],
//     verified: true,
//     responseTime: "45 mins",
//     email: "tasnim.rahman@carenow.com",
//     phone: "+8801712345686",
//     about:
//       "Nutrition specialist focusing on therapeutic diets and special nutritional needs.",
//     education: ["Nutrition Science Degree", "Dietitian Certification"],
//   },
//   {
//     id: "cg010",
//     name: "Salman Ahmed",
//     role: "Palliative Care Expert",
//     experience: "14 years",
//     rating: 4.9,
//     reviews: 118,
//     image: "https://randomuser.me/api/portraits/men/33.jpg",
//     specialties: ["Palliative Care", "Pain Management", "Comfort Care"],
//     hourlyRate: 600,
//     availability: "Full-time",
//     location: "Dhaka",
//     languages: ["Bangla", "English", "Arabic"],
//     verified: true,
//     responseTime: "20 mins",
//     email: "salman.ahmed@carenow.com",
//     phone: "+8801712345687",
//     about:
//       "Palliative care specialist with extensive experience in pain management and comfort care.",
//     education: ["Palliative Medicine", "Pain Management Certification"],
//   },
//   {
//     id: "cg011",
//     name: "Farida Begum",
//     role: "Maternity Care Nurse",
//     experience: "8 years",
//     rating: 4.7,
//     reviews: 89,
//     image: "https://randomuser.me/api/portraits/women/37.jpg",
//     specialties: ["Postpartum Care", "New Mother Support", "Breastfeeding"],
//     hourlyRate: 400,
//     availability: "Flexible",
//     location: "Barisal",
//     languages: ["Bangla", "English"],
//     verified: true,
//     responseTime: "35 mins",
//     email: "farida.begum@carenow.com",
//     phone: "+8801712345688",
//     about:
//       "Maternity care specialist supporting new mothers with postpartum care and breastfeeding.",
//     education: ["Midwifery", "Postpartum Care Certification"],
//   },
//   {
//     id: "cg012",
//     name: "Rashidul Islam",
//     role: "Mental Health Care",
//     experience: "10 years",
//     rating: 4.8,
//     reviews: 95,
//     image: "https://randomuser.me/api/portraits/men/66.jpg",
//     specialties: ["Mental Health Support", "Counseling", "Therapy Sessions"],
//     hourlyRate: 550,
//     availability: "Part-time",
//     location: "Dhaka",
//     languages: ["Bangla", "English"],
//     verified: true,
//     responseTime: "50 mins",
//     email: "rashidul.islam@carenow.com",
//     phone: "+8801712345689",
//     about:
//       "Mental health care professional providing counseling and therapeutic support.",
//     education: ["Clinical Psychology", "Counseling Certification"],
//   },
//   {
//     id: "cg013",
//     name: "Maya Rahman",
//     role: "Cancer Care Specialist",
//     experience: "9 years",
//     rating: 4.6,
//     reviews: 72,
//     image: "https://randomuser.me/api/portraits/women/29.jpg",
//     specialties: ["Oncology Care", "Chemotherapy Support", "Pain Management"],
//     hourlyRate: 580,
//     availability: "Full-time",
//     location: "Dhaka",
//     languages: ["Bangla", "English"],
//     verified: true,
//     responseTime: "25 mins",
//     email: "maya.rahman@carenow.com",
//     phone: "+8801712345690",
//     about:
//       "Oncology care specialist with expertise in chemotherapy support and cancer patient care.",
//     education: ["Oncology Nursing", "Cancer Care Certification"],
//   },
//   {
//     id: "cg014",
//     name: "Imran Hossain",
//     role: "Diabetes Care Expert",
//     experience: "7 years",
//     rating: 4.5,
//     reviews: 63,
//     image: "https://randomuser.me/api/portraits/men/52.jpg",
//     specialties: ["Diabetes Management", "Insulin Therapy", "Diet Control"],
//     hourlyRate: 420,
//     availability: "Flexible",
//     location: "Comilla",
//     languages: ["Bangla", "English"],
//     verified: true,
//     responseTime: "30 mins",
//     email: "imran.hossain@carenow.com",
//     phone: "+8801712345691",
//     about:
//       "Diabetes care specialist focusing on management, insulin therapy and diet control.",
//     education: ["Diabetes Educator", "Endocrinology Care"],
//   },
//   {
//     id: "cg015",
//     name: "Sadia Akter",
//     role: "General Care Nurse",
//     experience: "5 years",
//     rating: 4.4,
//     reviews: 58,
//     image: "https://randomuser.me/api/portraits/women/41.jpg",
//     specialties: ["General Nursing", "Medication Management", "Daily Care"],
//     hourlyRate: 300,
//     availability: "Full-time",
//     location: "Dhaka",
//     languages: ["Bangla", "English"],
//     verified: true,
//     responseTime: "20 mins",
//     email: "sadia.akter@carenow.com",
//     phone: "+8801712345692",
//     about:
//       "General care nurse providing comprehensive nursing care and medication management.",
//     education: ["General Nursing Diploma", "Patient Care Certification"],
//   },
// ];

// console.log("hello");

// const main = async () => {
//   try {
//     await client.connect();
//     const result = await dbConnect("caregivers").insertMany(caregiversData);
//     console.log("Caregivers seeded successfully", result);
//   } catch (error) {
//     console.log("Seeding error", error);
//   } finally {
//     await client.close();
//   }
// };

// main();
